-- Saves a catalog product into the user's wardrobe, refreshing the saved copy
-- when the catalog product changes. Keep query_params aliases in sync with
-- saveWardrobeItemFromCatalogByUrl in wardrobeCatalog.ts.
WITH query_params AS (
  SELECT
    -- Profile email that owns the saved catalog wardrobe item.
    $1::text AS profile_email,
    -- Catalog product URL used to find the source product and deduplicate wardrobe rows.
    $2::text AS product_url
)
INSERT INTO wardrobe (
  profile_email,
  product_id,
  name,
  url,
  description,
  brand,
  price,
  currency,
  availability,
  image_url,
  audience,
  category,
  season,
  formality_level,
  style,
  occasions,
  color_base,
  pattern,
  finish,
  is_neutral,
  composition,
  silhouette,
  fit,
  closure_type,
  embedding,
  source,
  processing_status
)
SELECT
  params.profile_email,
  products.id::text,
  products.name,
  products.url,
  products.description,
  products.brand,
  products.price,
  products.currency,
  products.availability,
  products.image_url,
  products.audience,
  products.category,
  products.season,
  products.formality_level,
  products.style,
  products.occasions,
  products.color_base,
  products.pattern,
  products.finish,
  products.is_neutral,
  products.composition,
  products.silhouette,
  products.fit,
  products.closure_type,
  products.embedding,
  'from_catalog',
  'ready'
FROM products
CROSS JOIN query_params AS params
WHERE products.url = params.product_url
ON CONFLICT (profile_email, url)
WHERE source = 'from_catalog' AND url IS NOT NULL
DO UPDATE SET
  product_id = excluded.product_id,
  name = excluded.name,
  description = excluded.description,
  brand = excluded.brand,
  price = excluded.price,
  currency = excluded.currency,
  availability = excluded.availability,
  image_url = excluded.image_url,
  audience = excluded.audience,
  category = excluded.category,
  season = excluded.season,
  formality_level = excluded.formality_level,
  style = excluded.style,
  occasions = excluded.occasions,
  color_base = excluded.color_base,
  pattern = excluded.pattern,
  finish = excluded.finish,
  is_neutral = excluded.is_neutral,
  composition = excluded.composition,
  silhouette = excluded.silhouette,
  fit = excluded.fit,
  closure_type = excluded.closure_type,
  embedding = excluded.embedding,
  processing_status = 'ready',
  updated_at = now()
RETURNING
  id,
  profile_email AS "profileEmail",
  product_id AS "productId",
  name,
  url,
  description,
  brand,
  price,
  currency,
  availability,
  image_url AS "imageUrl",
  audience,
  category,
  season,
  formality_level AS "formalityLevel",
  style,
  occasions,
  color_base AS "colorBase",
  pattern,
  finish,
  is_neutral AS "isNeutral",
  composition,
  silhouette,
  fit,
  closure_type AS "closureType",
  embedding,
  source,
  raw_image_url AS "rawImageUrl",
  processing_status AS "processingStatus",
  created_at AS "createdAt",
  updated_at AS "updatedAt"
