create table if not exists job_runs (
  id uuid primary key default gen_random_uuid(),
  provider_job_id text null,
  profile_email text not null,
  kind text not null,
  entity_type text null,
  entity_id text null,
  dedupe_key text null,
  status text not null,
  phase text null,
  progress_current integer not null default 0,
  progress_total integer null,
  progress_label text null,
  payload jsonb not null default '{}'::jsonb,
  result jsonb null,
  error_code text null,
  error_message text null,
  started_at timestamptz null,
  completed_at timestamptz null,
  failed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz null
)
