export {
  getSqlClient,
  setSqlClientOverride,
  stableStringify,
  hashCapsuleContent,
  hasAffectedRows,
} from "./db/core.js";
export { checkDatabaseConnection, ensureTables } from "./db/schema.js";
export {
  pruneLoginCodes,
  upsertLoginCode,
  getLoginCodeByEmail,
  verifyAndConsumeLoginCode,
  insertSession,
  getSessionById,
  deleteSessionById,
  pruneExpiredSessions,
  listPasskeysByEmail,
  insertPasskey,
  getPasskeyByCredentialId,
  updatePasskeyAuthentication,
  deletePasskeyByIdForEmail,
  insertPasskeyChallenge,
  consumePasskeyChallenge,
  pruneExpiredPasskeyChallenges,
} from "./db/auth.js";
export {
  hasProfileByEmail,
  getDistinctProductFormalityLevels,
  getDistinctProductOccasions,
  getDistinctProductSeasons,
  getDistinctProductPatterns,
  getDistinctProductBrands,
  getDistinctProductCategories,
  getDistinctProductSilhouettes,
  getDistinctProductFits,
  getDistinctProductClosureTypes,
  getDistinctProductColors,
  getProductPriceRange,
  getProductsByUrlsInOrder,
  getProductsWithEmbeddingsByUrlsInOrder,
} from "./db/productOptions.js";
export {
  buildPriceBuckets,
  getSearchByEmail,
  upsertSearchByEmail,
  searchProducts,
} from "./db/searchPersistence.js";
export { searchProductStats } from "./db/searchStats.js";
export {
  getProfileByEmail,
  createProfileRecord,
  updateProfileByEmail,
  updateProfileLocaleByEmail,
  updateProfileActiveCapsuleIdByEmail,
  createCapsuleRecord,
  getCapsuleByIdForEmail,
  listRecentCapsulesByEmail,
  searchCapsulesByEmail,
  listCapsuleNamesByEmail,
  updateCapsuleSnapshotByIdForEmail,
  renameCapsuleByIdForEmail,
  saveCapsuleByIdForEmail,
  revertCapsuleDraftByIdForEmail,
  deleteCapsuleByIdForEmail,
  upsertSharedCapsule,
  getValidSharedCapsuleById,
  pruneExpiredSharedCapsules,
  deleteProfileByEmail,
} from "./db/profileCapsules.js";
